language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - rustup component add rustfmt
script:
  - cargo build --all-features
  - cargo test --all-features
  - cargo fmt -- --check
